### ISSUE TITLE
Help starting the glitcher

### ISSUE THREAD

**Issue by thegreenonion** [antonxy/h264_glitcher#2]
Hello, can you create a video or a step by step manual how to start and use the h264 glitcher? Thank you, 
The Green Onion

**Comment by thegreenonion** [comment]
I get this error everytime:

     Running `target\release\h264_glitcher.exe -i videos\*`                                             thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src\bin\h264_glitcher.rs:166:41                                                                                               note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                           error: process didn't exit successfully: `target\release\h264_glitcher.exe -i videos\*` (exit code: 101)

**Comment by antonxy** [comment]
It would be nice to have more detailed instructions. However we are experimenting around with the code still, so instructions would probably get out of date quickly.

About your specific problem:
Looking at the referenced line
https://github.com/antonxy/h264_glitcher/blob/bae7ce88c064d6780fba8334b9a0ee40426fc8a2/src/bin/h264_glitcher.rs#L166
it looks like `paths` is empty. `paths` comes from the `-i` option. The `-i` option expects a list of files containing raw h264 streams.
If your `videos` folder contains them, the shell you are running the command on should expand `videos/*` into this list, which is apparently not happening.
Since you are on windows I guess you are running this in `cmd.exe` or PowerShell. I don't know how they behave with expansion of `*`. If your video files are in the correct location and it's not working, I would suggest running the command in Bash, for example using Git Bash.

**Comment by thegreenonion** [comment]
Thank you for the answer. When I delete the "target" folder and run the command "cargo run --release -- -i videos\* | mpv --no-correct-pts --fps=1000 --no-cache -" does it mean, the "videos" folder must be in the directory I run the command or in ".\target\release"? Is it better to run "cargo run --release -- -i C:\Users\...\Documents\GitHub\h264_glitcher\videos\* | mpv ..."?

**Comment by thegreenonion** [comment]
I runned it in Git bash and I now get the following error: 
Error: Os { code: 232, kind: BrokenPipe, message: "Die Pipe wird gerade geschlossen." }

eng: "The pipe is currently closing."

**Comment by thegreenonion** [comment]
The glitcher is now running in Git Bash. Thank you. But when I start touch OSC, and run h264_glitcher_default.tosc, nothing happens in mpv.

**Comment by antonxy** [comment]
Nice. Is the correct OSC address set in TouchOSC? The glitcher listens on port 8000 by default. Also make sure the firewall is not blocking it. Just opening and closing the connection settings in TouchOSC also helps sometimes, I guess it causes TouchOSC to reopen the connection.

**Comment by thegreenonion** [comment]
Thank you the glitcher is now running and listening on my touchosc commands. The "Select Video" section, how does it work? In the document tree there are only labels, no buttons and there is no reaction from the glitcher when I hit one of the buttons.

**Comment by thegreenonion** [comment]
I understood now, how the TouchOSC interface works. Thank you very much for your tip with the GitBash! Issue closed.
